TOKEN_BEGIN = "<BOS>"
TOKEN_END = "<EOS>"
TOKEN_UNKNOWN = "<UNK>"
TOKEN_PAD = "<PAD>"
TOKEN_SPACE = " "
SYMBOL_END_OF_WORD = "<w/>"

special_tokens = [
  TOKEN_BEGIN,
  TOKEN_END,
  TOKEN_UNKNOWN,
  TOKEN_PAD,
  TOKEN_SPACE,
  SYMBOL_END_OF_WORD
]